apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spire-integration-operator-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spire-integration-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
