{{- $fullname := include "spire.fullname" . }}
{{- $ns := .Release.Namespace }}
{{- $labels := include "spire.labels" . }}
{{- range .Values.imagePullSecrets }}
{{- $registryAuthDocument := dict -}}
{{- $authMessage := printf "%s:%s" .username .password | b64enc }}
{{- $_ := set $registryAuthDocument "auth" $authMessage }}
{{- $dockerAuthDocument := dict .registryURL $registryAuthDocument }}
{{- $dockerConfigJSONDocument := dict "auths" $dockerAuthDocument -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (printf "%s-%s" $fullname .name) }}
  namespace: {{ $ns }}
  labels:
    {{- $labels | nindent 4 }}
data:
  .dockerconfigjson: {{ $dockerConfigJSONDocument | toJson | b64enc | quote }}
type: kubernetes.io/dockerconfigjson
{{- end }}
