apiVersion: v1
kind: Namespace
metadata:
  name: go-spiffe-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: go-spiffe-tls
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        otterize/tls-secret-name: go-spiffe-tls-client-tls-secret
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: public.ecr.aws/e3b4k2v5/go-spiffe-client:latest
          volumeMounts:
            - name: spire-integration-tls
              mountPath: /etc/spire-integration
              readOnly: true
      volumes:
        - name: spire-integration-tls
          secret:
            secretName: go-spiffe-tls-client-tls-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: go-spiffe-tls
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        otterize/tls-secret-name: go-spiffe-tls-server-tls-secret
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 55555
          imagePullPolicy: Always
          image: public.ecr.aws/e3b4k2v5/go-spiffe-server:latest
          volumeMounts:
            - name: spire-integration-tls
              mountPath: /etc/spire-integration
              readOnly: true
      volumes:
        - name: spire-integration-tls
          secret:
            secretName: go-spiffe-tls-server-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: go-spiffe-server-service
  namespace: go-spiffe-tls
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: http
      port: 55555
      targetPort: 55555
