apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        otterize/service-name: go-spiffe-tls-client
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: public.ecr.aws/e3b4k2v5/go-spiffe-client:latest
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: spifferize-trust-bundle
              mountPath: /etc/spifferize/trust-bundle
              readOnly: true
            - name: spifferize-svid
              mountPath: /etc/spifferize/svid
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: spifferize-trust-bundle
          secret:
            secretName: spifferize-trust-bundle
        - name: spifferize-svid
          secret:
            secretName: spifferize-svid-go-spiffe-tls-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        otterize/service-name: go-spiffe-tls-server
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 55555
          imagePullPolicy: Always
          image: public.ecr.aws/e3b4k2v5/go-spiffe-server:latest
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: spifferize-trust-bundle
              mountPath: /etc/spifferize/trust-bundle
              readOnly: true
            - name: spifferize-svid
              mountPath: /etc/spifferize/svid
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: spifferize-trust-bundle
          secret:
            secretName: spifferize-trust-bundle
        - name: spifferize-svid
          secret:
            secretName: spifferize-svid-go-spiffe-tls-server

---
apiVersion: v1
kind: Service
metadata:
  name: go-spiffe-server-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: http
      port: 55555
      targetPort: 55555
