apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        otterize/tls-secret-name: spifferize-tls-go-spiffe-tls-client
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: public.ecr.aws/e3b4k2v5/go-spiffe-client:latest
          volumeMounts:
            - name: spifferize-tls
              mountPath: /etc/spifferize
              readOnly: true
      volumes:
        - name: spifferize-tls
          secret:
            secretName: spifferize-tls-go-spiffe-tls-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        otterize/tls-secret-name: spifferize-tls-go-spiffe-tls-server
    spec:
      containers:
        - name: server
          ports:
            - containerPort: 55555
          imagePullPolicy: Always
          image: public.ecr.aws/e3b4k2v5/go-spiffe-server:latest
          volumeMounts:
            - name: spifferize-tls
              mountPath: /etc/spifferize
              readOnly: true
      volumes:
        - name: spifferize-tls
          secret:
            secretName: spifferize-tls-go-spiffe-tls-server
---
apiVersion: v1
kind: Service
metadata:
  name: go-spiffe-server-service
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: http
      port: 55555
      targetPort: 55555
