name: Build
concurrency:
  group: "${{github.repository}}${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: us-central1-docker.pkg.dev/main-383408/otterize

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.registry.outputs.registry }} # workaround since env is not available outside of steps, i.e. in calling external workflows like we later do in e2e-test

    steps:
      - id: registry
        run: echo "registry=${{ env.REGISTRY }}" >> "$GITHUB_OUTPUT"

      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: network=host

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key_base64
          password: ${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: otterize
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Test
        uses: docker/build-push-action@v2
        with:
          context: src/operator
          file: src/operator/Dockerfile
          tags: ${{ env.REGISTRY }}/credentials-operator:${{ github.sha }}
          push: true
          network: host
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            "VERSION=0.0.${{ github.run_id }}"

  helm-e2e-test:
    uses: otterize/helm-charts/.github/workflows/e2e-test.yaml@949a04bfc6a23a936ec23b5ce0dbf62b33471f3e
    name: Trigger e2e tests from helm charts repo
    secrets: inherit
    with:
      github_ref: 949a04bfc6a23a936ec23b5ce0dbf62b33471f3e
      gcr-registry: ${{ needs.build.outputs.registry }}
      credentials-operator-tag: ${{ github.sha }}
    needs:
      - build

  tag-latest:
    name: Tag latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      # Push the Docker image to AWS ECR
      - name: Tag Images as latest
        run: |-
          retag_image_as_latest() { if [[ $(gcloud container images add-tag "${{ env.REGISTRY }}/$1:${{ github.sha }}" "${{ env.REGISTRY }}/$1:latest" --quiet) ]]; then echo "Failed tagging $1 as latest"; exit 1; fi } # using --quiet to avoid prompt
          retag_image_as_latest credentials-operator
